name: Create new realease

on:
  push:
    branches:
      - "**"
    tags:
      - "!**"

jobs:
  build:
    name: Build
    # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
    # runs-on: ubuntu-latest # Not working with  ubuntu-latest /  ubuntu-22.04
    # Error: /lib/x86_64-linux-gnu/libgio-2.0.so.0: undefined symbol: g_module_open_full
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@master

    - name: Install fuse and libfuse2
      run: |
        sudo apt install fuse libfuse2
        echo 'deb http://download.opensuse.org/repositories/home:/gottcode/xUbuntu_22.04/ /' | sudo tee /etc/apt/sources.list.d/home:gottcode.list
        curl -fsSL https://download.opensuse.org/repositories/home:gottcode/xUbuntu_22.04/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/home_gottcode.gpg > /dev/null
        sudo apt update
        #sudo apt install focuswriter

    - name: Get pkg2appimage
      run: |
        set -x
        wget https://github.com/AppImageCommunity/pkg2appimage/releases/download/continuous/pkg2appimage--x86_64.AppImage
        chmod +x pkg2appimage--x86_64.AppImage
        ls -lah

    - name: Make AppImage
      run:  |
        set -x
        ./pkg2appimage--x86_64.AppImage FocusWriter.yml

    - name: List files and rename AppImage
      run: |
        set -x
        pwd; ls -lah
        cd out/
        fileName=$(ls FocusWriter*.AppImage)
        echo "fileName: $fileName"
        fileNameNew=$(echo "$fileName" | sed 's/.AppImage//')
        mv "$fileName" "${fileNameNew}-1_JB.AppImage"
        md5sum "${fileNameNew}-1_JB.AppImage" > "${fileNameNew}-1_JB.AppImage.md5"
        ls -lah

    - uses: xresloader/upload-to-github-release@main
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          file: "out/FocusWriter-*.AppImage; out/FocusWriter-*.md5"
          release_id: ${{ steps.create_release.outputs.id }}
          verbose: true
          draft: false
